fastlane_version "2.66.2"

desc "Runs all the tests"
lane :test do |options|
    scan(
        project: options[:projectName],
        workspace: options[:workspaceName],
        device: options[:device],
        clean: true,
        prelaunch_simulator: true,
        output_directory: options[:reportPath],
        output_types: "html,junit"
    )
end

desc "Run test coverage"
lane :coverage do |options|
    slather(
        proj: options[:projectName],
        workspace: options[:workspaceName],
        input_format: "auto",
        source_directory: options[:sourcePath],
        output_directory: options[:reportPath],
        html: true,
        jenkins: true
    )
end
