#!groovy

pipeline {
  agent any

  environment {
    config = readJSON file: 'CI/config.json'
  }

  options {
    ansiColor("xterm")
  }

  stages {
    stage('SetUp') {
        steps {
            sh 'echo "We are ing SetUp stage"'
            sh 'echo ${config}'
            sh 'echo $PWD'
        }
    }
  
    stage('Tests') {
      steps {
        sh 'bundle exec fastlane test'
      }
    }
  }

  post {
    always {
    
      sh 'echo $PWD'
    
      // Processing test results
      junit 'build/results/scan/report.junit'
      
      // Cleanup
      sh 'rm -rf build'
    }
    
    success {
      sh 'echo "success :)"'
    }
    
    failure {
      sh 'echo "failure :("'
    }
  }
}
